## 1. Which base image do you want to use?


## 2. Set the working directory


## 3. Copy the project files into the working directory.


## 4. Install the dependencies


## 5. Document and inform the developer that the application will use PORT 5000 of the container.


## 6. Define the command to run when the container starts.
