## 1. Which base image do you want to use?

## 2. Set the working directory inside the container.

## 3. Copy your source code file to the working directory inside the container.

## 4. Define the command to run when the container starts.