## 1. Which base image do you want to use?

## 2. Set the working directory.

## 3. Copy the application's project files into the working directory.

## 4. Document and inform the developer that the application will use the container port: 8080.

## 5. Define the command to run when the container starts.
